#!/bin/sh
# $OpenBSD: Xsetup_0.in,v 1.1 2021/08/30 15:38:27 matthieu Exp $

prefix="/usr/X11R6"
exec_prefix="${prefix}"

xset fp+ /usr/local/share/fonts/terminus

# ${exec_prefix}/bin/xsetroot -fg \#6f6f6f -bg \#bfbfbf -bitmap ${prefix}/include/X11/bitmaps/root_weave
# ${exec_prefix}/bin/xsetroot -solid black
# ${exec_prefix}/bin/xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail

#  install package openbsd-backgrounds
#  then uncomment:
#if test -x /usr/local/bin/openbsd-wallpaper
#  then
# 	/usr/local/bin/openbsd-wallpaper
#fi

# sxpm OpenBSD.xpm &

export HOME=/home/egoodwin
if test -x /usr/local/bin/feh
  then
	/usr/local/bin/feh --bg-fill /home/egoodwin/wallpapers/pexels-eberhard.jpg
fi

# show the Sleep / Restart / Shutdown bar
# in case of sleep, pop xmessage again after waking up
(
while true; do
  xmessage -geometry +540-32 \
    -buttons "[ Sleep ]":20,"[ Restart ]":21,"[ Shutdown ]":22 ""
  ACTION=$?
  echo "Xmessage said: $ACTION"
  if   [ $ACTION -eq 20 ]; then /usr/sbin/zzz;
  elif [ $ACTION -eq 21 ]; then
    xsetroot -cursor_name watch
    /sbin/shutdown -r now
  elif [ $ACTION -eq 22 ]; then
    xsetroot -cursor_name watch
    /sbin/shutdown -p now
  else echo "Something bad happened to Xmessage.";
  fi
  # stop looping if xclock died (hopefully killed by GiveConsole)
  if [ -z "$(pgrep -U root xclock)" ]; then break; fi
done
) &

OS_NAME=$(uname -n)
OS_INFO=$(uname -smr)
xclock -geometry -0+0 -d -strftime "$OS_NAME ($OS_INFO) | %a. %d %b. %Y  %H:%M " &

