keyboard_layout:
  layout: us
  rules: evdev
  model: pc105
  
# extra_includes:
#  - "./personal/vscode_espanso.yml"
#  - "../match/personal/correspondence.yml"
#  - "../match/personal/egoodwin_espanso_root.yml"
#  - "../match/personal/_python_snippets.yml"