trigger: "pyhead"
replace: "it works!"
# form: 
#    '#---------------------------------------------------
#    # [[filename]].py
#    # project: [[projectname]]
#    # description: [[description]]
#    # init date: [[ddate]]
#    #
#    #---------------------------------------------------'

# form_fields:
#       text:
#         multiline: true