# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":raconv"
    replace: "Rana Analytics"

  - trigger: ":rallc"
    replace: "Rana Analytics, LLC"

  - trigger: ":raihconv"
    replace: "Rana International Holdings"

  - trigger: ":raihllc"
    replace: "Rana International Holdings, LLC" 

  - trigger: ":rasrv"
    replace: "Rana Servicios"

  - trigger: "fdate"
    replace: "{{filedate}}"
    vars:
      - name: filedate
        type: date
        params:
          format: "%Y%m%d"

  - trigger: "xdate"
    replace: "{{extenddate}}"
    vars:
      - name: extenddate
        type: date
        params:
          format: "%a %b %d, %Y"
  
  - trigger: "tdate"
    replace: "{{filedate}}"
    vars:
      - name: filedate
        type: date
        params:
          format: "%m.%d.%Y"

  - trigger: ":eag"
    replace: "Ed Goodwin"

  - trigger: ":rana"
    replace: "Rana Analytics"

  - trigger: ":cc"
    replace: "Coltwood Capital"

  - trigger: "fname"
    replace: "-eag-{{filedate}}."
    vars:
      - name: filedate
        type: date
        params:
          format: "%Y%m%d"